/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthorizationExceptionDto from '../model/AuthorizationExceptionDto';
import EvaluationConditionDto from '../model/EvaluationConditionDto';
import ExceptionDto from '../model/ExceptionDto';
import ProcessInstanceDto from '../model/ProcessInstanceDto';

/**
* Condition service.
* @module camunda-jssdk/ConditionApi
* @version 7.14.0
*/
export default class ConditionApi {

    /**
    * Constructs a new ConditionApi. 
    * @alias module:camunda-jssdk/ConditionApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Triggers evaluation of conditions for conditional start event(s).  Internally this maps to the engines condition evaluation builder method ConditionEvaluationBuilder#evaluateStartConditions().  For more information see the [Conditional Start Events](https://docs.camunda.org/manual/7.14/reference/bpmn20/events/conditional-events/#conditional-start-event) section of the [BPMN 2.0 Implementation Reference](https://docs.camunda.org/manual/7.14/reference/bpmn20/).
     * @param {Object} opts Optional parameters
     * @param {module:model/EvaluationConditionDto} opts.evaluationConditionDto 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/ProcessInstanceDto>} and HTTP response
     */
    evaluateConditionWithHttpInfo(opts) {
      opts = opts || {};
      let postBody = opts['evaluationConditionDto'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [ProcessInstanceDto];
      return this.apiClient.callApi(
        '/condition', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Triggers evaluation of conditions for conditional start event(s).  Internally this maps to the engines condition evaluation builder method ConditionEvaluationBuilder#evaluateStartConditions().  For more information see the [Conditional Start Events](https://docs.camunda.org/manual/7.14/reference/bpmn20/events/conditional-events/#conditional-start-event) section of the [BPMN 2.0 Implementation Reference](https://docs.camunda.org/manual/7.14/reference/bpmn20/).
     * @param {Object} opts Optional parameters
     * @param {module:model/EvaluationConditionDto} opts.evaluationConditionDto 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/ProcessInstanceDto>}
     */
    evaluateCondition(opts) {
      return this.evaluateConditionWithHttpInfo(opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
