/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CaseDefinitionDto model module.
 * @module model/CaseDefinitionDto
 * @version 7.14.0
 */
class CaseDefinitionDto {
    /**
     * Constructs a new <code>CaseDefinitionDto</code>.
     * @alias module:model/CaseDefinitionDto
     */
    constructor() { 
        
        CaseDefinitionDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CaseDefinitionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CaseDefinitionDto} obj Optional instance to populate.
     * @return {module:model/CaseDefinitionDto} The populated <code>CaseDefinitionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CaseDefinitionDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('key')) {
                obj['key'] = ApiClient.convertToType(data['key'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('resource')) {
                obj['resource'] = ApiClient.convertToType(data['resource'], 'String');
            }
            if (data.hasOwnProperty('deploymentId')) {
                obj['deploymentId'] = ApiClient.convertToType(data['deploymentId'], 'String');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('historyTimeToLive')) {
                obj['historyTimeToLive'] = ApiClient.convertToType(data['historyTimeToLive'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The id of the case definition
 * @member {String} id
 */
CaseDefinitionDto.prototype['id'] = undefined;

/**
 * The key of the case definition, i.e., the id of the CMMN 2.0 XML case definition.
 * @member {String} key
 */
CaseDefinitionDto.prototype['key'] = undefined;

/**
 * The category of the case definition.
 * @member {String} category
 */
CaseDefinitionDto.prototype['category'] = undefined;

/**
 * The name of the case definition.
 * @member {String} name
 */
CaseDefinitionDto.prototype['name'] = undefined;

/**
 * The version of the case definition that the engine assigned to it.
 * @member {Number} version
 */
CaseDefinitionDto.prototype['version'] = undefined;

/**
 * The file name of the case definition.
 * @member {String} resource
 */
CaseDefinitionDto.prototype['resource'] = undefined;

/**
 * The deployment id of the case definition.
 * @member {String} deploymentId
 */
CaseDefinitionDto.prototype['deploymentId'] = undefined;

/**
 * The tenant id of the case definition.
 * @member {String} tenantId
 */
CaseDefinitionDto.prototype['tenantId'] = undefined;

/**
 * History time to live value of the case definition. Is used within [History cleanup](https://docs.camunda.org/manual/7.14/user-guide/process-engine/history/#history-cleanup).
 * @member {Number} historyTimeToLive
 */
CaseDefinitionDto.prototype['historyTimeToLive'] = undefined;






export default CaseDefinitionDto;

