/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeploymentResourceDto model module.
 * @module model/DeploymentResourceDto
 * @version 7.14.0
 */
class DeploymentResourceDto {
    /**
     * Constructs a new <code>DeploymentResourceDto</code>.
     * A JSON object corresponding to the &#x60;Resource&#x60; interface in the engine. Its properties are as follows:
     * @alias module:model/DeploymentResourceDto
     */
    constructor() { 
        
        DeploymentResourceDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DeploymentResourceDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeploymentResourceDto} obj Optional instance to populate.
     * @return {module:model/DeploymentResourceDto} The populated <code>DeploymentResourceDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeploymentResourceDto();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('deploymentId')) {
                obj['deploymentId'] = ApiClient.convertToType(data['deploymentId'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The id of the deployment resource.
 * @member {String} id
 */
DeploymentResourceDto.prototype['id'] = undefined;

/**
 * The name of the deployment resource
 * @member {String} name
 */
DeploymentResourceDto.prototype['name'] = undefined;

/**
 * The id of the deployment.
 * @member {String} deploymentId
 */
DeploymentResourceDto.prototype['deploymentId'] = undefined;






export default DeploymentResourceDto;

