/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExceptionDto model module.
 * @module model/ExceptionDto
 * @version 7.14.0
 */
class ExceptionDto {
    /**
     * Constructs a new <code>ExceptionDto</code>.
     * @alias module:model/ExceptionDto
     */
    constructor() { 
        
        ExceptionDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExceptionDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExceptionDto} obj Optional instance to populate.
     * @return {module:model/ExceptionDto} The populated <code>ExceptionDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExceptionDto();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * An exception class indicating the occurred error.
 * @member {String} type
 */
ExceptionDto.prototype['type'] = undefined;

/**
 * A detailed message of the error.
 * @member {String} message
 */
ExceptionDto.prototype['message'] = undefined;






export default ExceptionDto;

