/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExternalTaskQueryDtoSorting model module.
 * @module model/ExternalTaskQueryDtoSorting
 * @version 7.14.0
 */
class ExternalTaskQueryDtoSorting {
    /**
     * Constructs a new <code>ExternalTaskQueryDtoSorting</code>.
     * @alias module:model/ExternalTaskQueryDtoSorting
     */
    constructor() { 
        
        ExternalTaskQueryDtoSorting.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExternalTaskQueryDtoSorting</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExternalTaskQueryDtoSorting} obj Optional instance to populate.
     * @return {module:model/ExternalTaskQueryDtoSorting} The populated <code>ExternalTaskQueryDtoSorting</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExternalTaskQueryDtoSorting();

            if (data.hasOwnProperty('sortBy')) {
                obj['sortBy'] = ApiClient.convertToType(data['sortBy'], 'String');
            }
            if (data.hasOwnProperty('sortOrder')) {
                obj['sortOrder'] = ApiClient.convertToType(data['sortOrder'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Sort the results lexicographically by a given criterion. Must be used in conjunction with the sortOrder parameter.
 * @member {module:model/ExternalTaskQueryDtoSorting.SortByEnum} sortBy
 */
ExternalTaskQueryDtoSorting.prototype['sortBy'] = undefined;

/**
 * Sort the results in a given order. Values may be `asc` for ascending order or `desc` for descending order. Must be used in conjunction with the sortBy parameter.
 * @member {module:model/ExternalTaskQueryDtoSorting.SortOrderEnum} sortOrder
 */
ExternalTaskQueryDtoSorting.prototype['sortOrder'] = undefined;





/**
 * Allowed values for the <code>sortBy</code> property.
 * @enum {String}
 * @readonly
 */
ExternalTaskQueryDtoSorting['SortByEnum'] = {

    /**
     * value: "id"
     * @const
     */
    "id": "id",

    /**
     * value: "lockExpirationTime"
     * @const
     */
    "lockExpirationTime": "lockExpirationTime",

    /**
     * value: "processInstanceId"
     * @const
     */
    "processInstanceId": "processInstanceId",

    /**
     * value: "processDefinitionId"
     * @const
     */
    "processDefinitionId": "processDefinitionId",

    /**
     * value: "processDefinitionKey"
     * @const
     */
    "processDefinitionKey": "processDefinitionKey",

    /**
     * value: "taskPriority"
     * @const
     */
    "taskPriority": "taskPriority",

    /**
     * value: "tenantId"
     * @const
     */
    "tenantId": "tenantId"
};


/**
 * Allowed values for the <code>sortOrder</code> property.
 * @enum {String}
 * @readonly
 */
ExternalTaskQueryDtoSorting['SortOrderEnum'] = {

    /**
     * value: "asc"
     * @const
     */
    "asc": "asc",

    /**
     * value: "desc"
     * @const
     */
    "desc": "desc"
};



export default ExternalTaskQueryDtoSorting;

