/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExternalTaskBpmnErrorAllOf from './ExternalTaskBpmnErrorAllOf';
import TaskBpmnErrorDto from './TaskBpmnErrorDto';
import VariableValueDto from './VariableValueDto';

/**
 * The ExternalTaskBpmnError model module.
 * @module model/ExternalTaskBpmnError
 * @version 7.14.0
 */
class ExternalTaskBpmnError {
    /**
     * Constructs a new <code>ExternalTaskBpmnError</code>.
     * @alias module:model/ExternalTaskBpmnError
     * @implements module:model/ExternalTaskBpmnErrorAllOf
     * @implements module:model/TaskBpmnErrorDto
     */
    constructor() { 
        ExternalTaskBpmnErrorAllOf.initialize(this);TaskBpmnErrorDto.initialize(this);
        ExternalTaskBpmnError.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExternalTaskBpmnError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExternalTaskBpmnError} obj Optional instance to populate.
     * @return {module:model/ExternalTaskBpmnError} The populated <code>ExternalTaskBpmnError</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExternalTaskBpmnError();
            ExternalTaskBpmnErrorAllOf.constructFromObject(data, obj);
            TaskBpmnErrorDto.constructFromObject(data, obj);

            if (data.hasOwnProperty('workerId')) {
                obj['workerId'] = ApiClient.convertToType(data['workerId'], 'String');
            }
            if (data.hasOwnProperty('errorCode')) {
                obj['errorCode'] = ApiClient.convertToType(data['errorCode'], 'String');
            }
            if (data.hasOwnProperty('errorMessage')) {
                obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], {'String': VariableValueDto});
            }
        }
        return obj;
    }


}

/**
 * The id of the worker that reports the failure. Must match the id of the worker who has most recently locked the task.
 * @member {String} workerId
 */
ExternalTaskBpmnError.prototype['workerId'] = undefined;

/**
 * An error code that indicates the predefined error. It is used to identify the BPMN error handler.
 * @member {String} errorCode
 */
ExternalTaskBpmnError.prototype['errorCode'] = undefined;

/**
 * An error message that describes the error.
 * @member {String} errorMessage
 */
ExternalTaskBpmnError.prototype['errorMessage'] = undefined;

/**
 * A JSON object containing variable key-value pairs.
 * @member {Object.<String, module:model/VariableValueDto>} variables
 */
ExternalTaskBpmnError.prototype['variables'] = undefined;


// Implement ExternalTaskBpmnErrorAllOf interface:
/**
 * The id of the worker that reports the failure. Must match the id of the worker who has most recently locked the task.
 * @member {String} workerId
 */
ExternalTaskBpmnErrorAllOf.prototype['workerId'] = undefined;
// Implement TaskBpmnErrorDto interface:
/**
 * An error code that indicates the predefined error. It is used to identify the BPMN error handler.
 * @member {String} errorCode
 */
TaskBpmnErrorDto.prototype['errorCode'] = undefined;
/**
 * An error message that describes the error.
 * @member {String} errorMessage
 */
TaskBpmnErrorDto.prototype['errorMessage'] = undefined;
/**
 * A JSON object containing variable key-value pairs.
 * @member {Object.<String, module:model/VariableValueDto>} variables
 */
TaskBpmnErrorDto.prototype['variables'] = undefined;




export default ExternalTaskBpmnError;

