/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MetricsResultDto model module.
 * @module model/MetricsResultDto
 * @version 7.14.0
 */
class MetricsResultDto {
    /**
     * Constructs a new <code>MetricsResultDto</code>.
     * @alias module:model/MetricsResultDto
     */
    constructor() { 
        
        MetricsResultDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MetricsResultDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MetricsResultDto} obj Optional instance to populate.
     * @return {module:model/MetricsResultDto} The populated <code>MetricsResultDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MetricsResultDto();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The current sum (count) for the selected metric.
 * @member {Number} result
 */
MetricsResultDto.prototype['result'] = undefined;






export default MetricsResultDto;

