/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResourceReportDto from './ResourceReportDto';

/**
 * The ParseExceptionDtoAllOf model module.
 * @module model/ParseExceptionDtoAllOf
 * @version 7.14.0
 */
class ParseExceptionDtoAllOf {
    /**
     * Constructs a new <code>ParseExceptionDtoAllOf</code>.
     * @alias module:model/ParseExceptionDtoAllOf
     */
    constructor() { 
        
        ParseExceptionDtoAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ParseExceptionDtoAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ParseExceptionDtoAllOf} obj Optional instance to populate.
     * @return {module:model/ParseExceptionDtoAllOf} The populated <code>ParseExceptionDtoAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ParseExceptionDtoAllOf();

            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], {'String': ResourceReportDto});
            }
        }
        return obj;
    }


}

/**
 * A JSON Object containing list of errors and warnings occurred during deployment.
 * @member {Object.<String, module:model/ResourceReportDto>} details
 */
ParseExceptionDtoAllOf.prototype['details'] = undefined;






export default ParseExceptionDtoAllOf;

