/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProcessEngineDto model module.
 * @module model/ProcessEngineDto
 * @version 7.14.0
 */
class ProcessEngineDto {
    /**
     * Constructs a new <code>ProcessEngineDto</code>.
     * @alias module:model/ProcessEngineDto
     */
    constructor() { 
        
        ProcessEngineDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProcessEngineDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProcessEngineDto} obj Optional instance to populate.
     * @return {module:model/ProcessEngineDto} The populated <code>ProcessEngineDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcessEngineDto();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The name of the process engine.
 * @member {String} name
 */
ProcessEngineDto.prototype['name'] = undefined;






export default ProcessEngineDto;

