/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProcessInstanceModificationInstructionDto from './ProcessInstanceModificationInstructionDto';

/**
 * The ProcessInstanceModificationDto model module.
 * @module model/ProcessInstanceModificationDto
 * @version 7.14.0
 */
class ProcessInstanceModificationDto {
    /**
     * Constructs a new <code>ProcessInstanceModificationDto</code>.
     * @alias module:model/ProcessInstanceModificationDto
     */
    constructor() { 
        
        ProcessInstanceModificationDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProcessInstanceModificationDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProcessInstanceModificationDto} obj Optional instance to populate.
     * @return {module:model/ProcessInstanceModificationDto} The populated <code>ProcessInstanceModificationDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProcessInstanceModificationDto();

            if (data.hasOwnProperty('skipCustomListeners')) {
                obj['skipCustomListeners'] = ApiClient.convertToType(data['skipCustomListeners'], 'Boolean');
            }
            if (data.hasOwnProperty('skipIoMappings')) {
                obj['skipIoMappings'] = ApiClient.convertToType(data['skipIoMappings'], 'Boolean');
            }
            if (data.hasOwnProperty('instructions')) {
                obj['instructions'] = ApiClient.convertToType(data['instructions'], [ProcessInstanceModificationInstructionDto]);
            }
            if (data.hasOwnProperty('annotation')) {
                obj['annotation'] = ApiClient.convertToType(data['annotation'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Skip execution listener invocation for activities that are started or ended as part of this request.
 * @member {Boolean} skipCustomListeners
 */
ProcessInstanceModificationDto.prototype['skipCustomListeners'] = undefined;

/**
 * Skip execution of [input/output variable mappings](https://docs.camunda.org/manual/7.14/user-guide/process-engine/variables/#input-output-variable-mapping) for activities that are started or ended as part of this request.
 * @member {Boolean} skipIoMappings
 */
ProcessInstanceModificationDto.prototype['skipIoMappings'] = undefined;

/**
 * JSON array of modification instructions. The instructions are executed in the order they are in.
 * @member {Array.<module:model/ProcessInstanceModificationInstructionDto>} instructions
 */
ProcessInstanceModificationDto.prototype['instructions'] = undefined;

/**
 * An arbitrary text annotation set by a user for auditing reasons.
 * @member {String} annotation
 */
ProcessInstanceModificationDto.prototype['annotation'] = undefined;






export default ProcessInstanceModificationDto;

