/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RetriesDto model module.
 * @module model/RetriesDto
 * @version 7.14.0
 */
class RetriesDto {
    /**
     * Constructs a new <code>RetriesDto</code>.
     * @alias module:model/RetriesDto
     */
    constructor() { 
        
        RetriesDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RetriesDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RetriesDto} obj Optional instance to populate.
     * @return {module:model/RetriesDto} The populated <code>RetriesDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RetriesDto();

            if (data.hasOwnProperty('retries')) {
                obj['retries'] = ApiClient.convertToType(data['retries'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * The number of retries to set for the resource.  Must be >= 0. If this is 0, an incident is created and the task, or job, cannot be fetched, or acquired anymore unless the retries are increased again. Can not be null.
 * @member {Number} retries
 */
RetriesDto.prototype['retries'] = undefined;






export default RetriesDto;

