/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ExternalTaskQueryDto from './ExternalTaskQueryDto';
import HistoricProcessInstanceQueryDto from './HistoricProcessInstanceQueryDto';
import ProcessInstanceQueryDto from './ProcessInstanceQueryDto';

/**
 * The SetRetriesForExternalTasksDto model module.
 * @module model/SetRetriesForExternalTasksDto
 * @version 7.14.0
 */
class SetRetriesForExternalTasksDto {
    /**
     * Constructs a new <code>SetRetriesForExternalTasksDto</code>.
     * @alias module:model/SetRetriesForExternalTasksDto
     */
    constructor() { 
        
        SetRetriesForExternalTasksDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SetRetriesForExternalTasksDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetRetriesForExternalTasksDto} obj Optional instance to populate.
     * @return {module:model/SetRetriesForExternalTasksDto} The populated <code>SetRetriesForExternalTasksDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetRetriesForExternalTasksDto();

            if (data.hasOwnProperty('retries')) {
                obj['retries'] = ApiClient.convertToType(data['retries'], 'Number');
            }
            if (data.hasOwnProperty('externalTaskIds')) {
                obj['externalTaskIds'] = ApiClient.convertToType(data['externalTaskIds'], ['String']);
            }
            if (data.hasOwnProperty('processInstanceIds')) {
                obj['processInstanceIds'] = ApiClient.convertToType(data['processInstanceIds'], ['String']);
            }
            if (data.hasOwnProperty('externalTaskQuery')) {
                obj['externalTaskQuery'] = ExternalTaskQueryDto.constructFromObject(data['externalTaskQuery']);
            }
            if (data.hasOwnProperty('processInstanceQuery')) {
                obj['processInstanceQuery'] = ProcessInstanceQueryDto.constructFromObject(data['processInstanceQuery']);
            }
            if (data.hasOwnProperty('historicProcessInstanceQuery')) {
                obj['historicProcessInstanceQuery'] = HistoricProcessInstanceQueryDto.constructFromObject(data['historicProcessInstanceQuery']);
            }
        }
        return obj;
    }


}

/**
 * The number of retries to set for the external task.  Must be >= 0. If this is 0, an incident is created and the task cannot be fetched anymore unless the retries are increased again. Can not be null.
 * @member {Number} retries
 */
SetRetriesForExternalTasksDto.prototype['retries'] = undefined;

/**
 * The ids of the external tasks to set the number of retries for.
 * @member {Array.<String>} externalTaskIds
 */
SetRetriesForExternalTasksDto.prototype['externalTaskIds'] = undefined;

/**
 * The ids of process instances containing the tasks to set the number of retries for.
 * @member {Array.<String>} processInstanceIds
 */
SetRetriesForExternalTasksDto.prototype['processInstanceIds'] = undefined;

/**
 * @member {module:model/ExternalTaskQueryDto} externalTaskQuery
 */
SetRetriesForExternalTasksDto.prototype['externalTaskQuery'] = undefined;

/**
 * @member {module:model/ProcessInstanceQueryDto} processInstanceQuery
 */
SetRetriesForExternalTasksDto.prototype['processInstanceQuery'] = undefined;

/**
 * @member {module:model/HistoricProcessInstanceQueryDto} historicProcessInstanceQuery
 */
SetRetriesForExternalTasksDto.prototype['historicProcessInstanceQuery'] = undefined;






export default SetRetriesForExternalTasksDto;

