/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AbstractSetRemovalTimeDto from './AbstractSetRemovalTimeDto';
import HistoricProcessInstanceQueryDto from './HistoricProcessInstanceQueryDto';
import SetRemovalTimeToHistoricProcessInstancesDtoAllOf from './SetRemovalTimeToHistoricProcessInstancesDtoAllOf';

/**
 * The SetRemovalTimeToHistoricProcessInstancesDto model module.
 * @module model/SetRemovalTimeToHistoricProcessInstancesDto
 * @version 7.14.0
 */
class SetRemovalTimeToHistoricProcessInstancesDto {
    /**
     * Constructs a new <code>SetRemovalTimeToHistoricProcessInstancesDto</code>.
     * @alias module:model/SetRemovalTimeToHistoricProcessInstancesDto
     * @implements module:model/SetRemovalTimeToHistoricProcessInstancesDtoAllOf
     * @implements module:model/AbstractSetRemovalTimeDto
     */
    constructor() { 
        SetRemovalTimeToHistoricProcessInstancesDtoAllOf.initialize(this);AbstractSetRemovalTimeDto.initialize(this);
        SetRemovalTimeToHistoricProcessInstancesDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SetRemovalTimeToHistoricProcessInstancesDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SetRemovalTimeToHistoricProcessInstancesDto} obj Optional instance to populate.
     * @return {module:model/SetRemovalTimeToHistoricProcessInstancesDto} The populated <code>SetRemovalTimeToHistoricProcessInstancesDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SetRemovalTimeToHistoricProcessInstancesDto();
            SetRemovalTimeToHistoricProcessInstancesDtoAllOf.constructFromObject(data, obj);
            AbstractSetRemovalTimeDto.constructFromObject(data, obj);

            if (data.hasOwnProperty('historicProcessInstanceIds')) {
                obj['historicProcessInstanceIds'] = ApiClient.convertToType(data['historicProcessInstanceIds'], ['String']);
            }
            if (data.hasOwnProperty('historicProcessInstanceQuery')) {
                obj['historicProcessInstanceQuery'] = HistoricProcessInstanceQueryDto.constructFromObject(data['historicProcessInstanceQuery']);
            }
            if (data.hasOwnProperty('hierarchical')) {
                obj['hierarchical'] = ApiClient.convertToType(data['hierarchical'], 'Boolean');
            }
            if (data.hasOwnProperty('absoluteRemovalTime')) {
                obj['absoluteRemovalTime'] = ApiClient.convertToType(data['absoluteRemovalTime'], 'Date');
            }
            if (data.hasOwnProperty('clearedRemovalTime')) {
                obj['clearedRemovalTime'] = ApiClient.convertToType(data['clearedRemovalTime'], 'Boolean');
            }
            if (data.hasOwnProperty('calculatedRemovalTime')) {
                obj['calculatedRemovalTime'] = ApiClient.convertToType(data['calculatedRemovalTime'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The id of the process instance.
 * @member {Array.<String>} historicProcessInstanceIds
 */
SetRemovalTimeToHistoricProcessInstancesDto.prototype['historicProcessInstanceIds'] = undefined;

/**
 * @member {module:model/HistoricProcessInstanceQueryDto} historicProcessInstanceQuery
 */
SetRemovalTimeToHistoricProcessInstancesDto.prototype['historicProcessInstanceQuery'] = undefined;

/**
 * Sets the removal time to all historic process instances in the hierarchy. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} hierarchical
 */
SetRemovalTimeToHistoricProcessInstancesDto.prototype['hierarchical'] = undefined;

/**
 * The date for which the instances shall be removed. Value may not be `null`.  **Note:** Cannot be set in conjunction with `clearedRemovalTime` or `calculatedRemovalTime`.
 * @member {Date} absoluteRemovalTime
 */
SetRemovalTimeToHistoricProcessInstancesDto.prototype['absoluteRemovalTime'] = undefined;

/**
 * Sets the removal time to `null`. Value may only be `true`, as `false` is the default behavior.  **Note:** Cannot be set in conjunction with `absoluteRemovalTime` or `calculatedRemovalTime`.
 * @member {Boolean} clearedRemovalTime
 */
SetRemovalTimeToHistoricProcessInstancesDto.prototype['clearedRemovalTime'] = undefined;

/**
 * The removal time is calculated based on the engine's configuration settings. Value may only be `true`, as `false` is the default behavior.  **Note:** Cannot be set in conjunction with `absoluteRemovalTime` or `clearedRemovalTime`.
 * @member {Boolean} calculatedRemovalTime
 */
SetRemovalTimeToHistoricProcessInstancesDto.prototype['calculatedRemovalTime'] = undefined;


// Implement SetRemovalTimeToHistoricProcessInstancesDtoAllOf interface:
/**
 * The id of the process instance.
 * @member {Array.<String>} historicProcessInstanceIds
 */
SetRemovalTimeToHistoricProcessInstancesDtoAllOf.prototype['historicProcessInstanceIds'] = undefined;
/**
 * @member {module:model/HistoricProcessInstanceQueryDto} historicProcessInstanceQuery
 */
SetRemovalTimeToHistoricProcessInstancesDtoAllOf.prototype['historicProcessInstanceQuery'] = undefined;
/**
 * Sets the removal time to all historic process instances in the hierarchy. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} hierarchical
 */
SetRemovalTimeToHistoricProcessInstancesDtoAllOf.prototype['hierarchical'] = undefined;
// Implement AbstractSetRemovalTimeDto interface:
/**
 * The date for which the instances shall be removed. Value may not be `null`.  **Note:** Cannot be set in conjunction with `clearedRemovalTime` or `calculatedRemovalTime`.
 * @member {Date} absoluteRemovalTime
 */
AbstractSetRemovalTimeDto.prototype['absoluteRemovalTime'] = undefined;
/**
 * Sets the removal time to `null`. Value may only be `true`, as `false` is the default behavior.  **Note:** Cannot be set in conjunction with `absoluteRemovalTime` or `calculatedRemovalTime`.
 * @member {Boolean} clearedRemovalTime
 */
AbstractSetRemovalTimeDto.prototype['clearedRemovalTime'] = undefined;
/**
 * The removal time is calculated based on the engine's configuration settings. Value may only be `true`, as `false` is the default behavior.  **Note:** Cannot be set in conjunction with `absoluteRemovalTime` or `clearedRemovalTime`.
 * @member {Boolean} calculatedRemovalTime
 */
AbstractSetRemovalTimeDto.prototype['calculatedRemovalTime'] = undefined;




export default SetRemovalTimeToHistoricProcessInstancesDto;

