/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SortTaskQueryParametersDto model module.
 * @module model/SortTaskQueryParametersDto
 * @version 7.14.0
 */
class SortTaskQueryParametersDto {
    /**
     * Constructs a new <code>SortTaskQueryParametersDto</code>.
     * Mandatory when &#x60;sortBy&#x60; is one of the following values: &#x60;processVariable&#x60;, &#x60;executionVariable&#x60;, &#x60;taskVariable&#x60;, &#x60;caseExecutionVariable&#x60; or &#x60;caseInstanceVariable&#x60;. Must be a JSON object with the properties &#x60;variable&#x60; and &#x60;type&#x60; where &#x60;variable&#x60; is a variable name and &#x60;type&#x60; is the name of a variable value type.
     * @alias module:model/SortTaskQueryParametersDto
     */
    constructor() { 
        
        SortTaskQueryParametersDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SortTaskQueryParametersDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SortTaskQueryParametersDto} obj Optional instance to populate.
     * @return {module:model/SortTaskQueryParametersDto} The populated <code>SortTaskQueryParametersDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SortTaskQueryParametersDto();

            if (data.hasOwnProperty('variable')) {
                obj['variable'] = ApiClient.convertToType(data['variable'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The name of the variable to sort by.
 * @member {String} variable
 */
SortTaskQueryParametersDto.prototype['variable'] = undefined;

/**
 * The name of the type of the variable value.
 * @member {String} type
 */
SortTaskQueryParametersDto.prototype['type'] = undefined;






export default SortTaskQueryParametersDto;

