/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProcessInstanceModificationInstructionDto from './ProcessInstanceModificationInstructionDto';
import VariableValueDto from './VariableValueDto';

/**
 * The StartProcessInstanceDto model module.
 * @module model/StartProcessInstanceDto
 * @version 7.14.0
 */
class StartProcessInstanceDto {
    /**
     * Constructs a new <code>StartProcessInstanceDto</code>.
     * @alias module:model/StartProcessInstanceDto
     */
    constructor() { 
        
        StartProcessInstanceDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>StartProcessInstanceDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StartProcessInstanceDto} obj Optional instance to populate.
     * @return {module:model/StartProcessInstanceDto} The populated <code>StartProcessInstanceDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StartProcessInstanceDto();

            if (data.hasOwnProperty('businessKey')) {
                obj['businessKey'] = ApiClient.convertToType(data['businessKey'], 'String');
            }
            if (data.hasOwnProperty('variables')) {
                obj['variables'] = ApiClient.convertToType(data['variables'], {'String': VariableValueDto});
            }
            if (data.hasOwnProperty('caseInstanceId')) {
                obj['caseInstanceId'] = ApiClient.convertToType(data['caseInstanceId'], 'String');
            }
            if (data.hasOwnProperty('startInstructions')) {
                obj['startInstructions'] = ApiClient.convertToType(data['startInstructions'], [ProcessInstanceModificationInstructionDto]);
            }
            if (data.hasOwnProperty('skipCustomListeners')) {
                obj['skipCustomListeners'] = ApiClient.convertToType(data['skipCustomListeners'], 'Boolean');
            }
            if (data.hasOwnProperty('skipIoMappings')) {
                obj['skipIoMappings'] = ApiClient.convertToType(data['skipIoMappings'], 'Boolean');
            }
            if (data.hasOwnProperty('withVariablesInReturn')) {
                obj['withVariablesInReturn'] = ApiClient.convertToType(data['withVariablesInReturn'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * The business key of the process instance.
 * @member {String} businessKey
 */
StartProcessInstanceDto.prototype['businessKey'] = undefined;

/**
 * @member {Object.<String, module:model/VariableValueDto>} variables
 */
StartProcessInstanceDto.prototype['variables'] = undefined;

/**
 * The case instance id the process instance is to be initialized with.
 * @member {String} caseInstanceId
 */
StartProcessInstanceDto.prototype['caseInstanceId'] = undefined;

/**
 * **Optional**. A JSON array of instructions that specify which activities to start the process instance at. If this property is omitted, the process instance starts at its default blank start event.
 * @member {Array.<module:model/ProcessInstanceModificationInstructionDto>} startInstructions
 */
StartProcessInstanceDto.prototype['startInstructions'] = undefined;

/**
 * Skip execution listener invocation for activities that are started or ended as part of this request. **Note**: This option is currently only respected when start instructions are submitted via the `startInstructions` property.
 * @member {Boolean} skipCustomListeners
 */
StartProcessInstanceDto.prototype['skipCustomListeners'] = undefined;

/**
 * Skip execution of [input/output variable mappings](https://docs.camunda.org/manual/7.14/user-guide/process-engine/variables/#input-output-variable-mapping) for activities that are started or ended as part of this request. **Note**: This option is currently only respected when start instructions are submitted via the `startInstructions` property.
 * @member {Boolean} skipIoMappings
 */
StartProcessInstanceDto.prototype['skipIoMappings'] = undefined;

/**
 * Indicates if the variables, which was used by the process instance during execution, should be returned. Default value: `false`
 * @member {Boolean} withVariablesInReturn
 */
StartProcessInstanceDto.prototype['withVariablesInReturn'] = undefined;






export default StartProcessInstanceDto;

