/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TaskQueryDtoSorting from './TaskQueryDtoSorting';
import VariableQueryParameterDto from './VariableQueryParameterDto';

/**
 * The TaskQueryDto model module.
 * @module model/TaskQueryDto
 * @version 7.14.0
 */
class TaskQueryDto {
    /**
     * Constructs a new <code>TaskQueryDto</code>.
     * A Task query which defines a group of Tasks.
     * @alias module:model/TaskQueryDto
     */
    constructor() { 
        
        TaskQueryDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TaskQueryDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TaskQueryDto} obj Optional instance to populate.
     * @return {module:model/TaskQueryDto} The populated <code>TaskQueryDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaskQueryDto();

            if (data.hasOwnProperty('processInstanceId')) {
                obj['processInstanceId'] = ApiClient.convertToType(data['processInstanceId'], 'String');
            }
            if (data.hasOwnProperty('processInstanceIdIn')) {
                obj['processInstanceIdIn'] = ApiClient.convertToType(data['processInstanceIdIn'], ['String']);
            }
            if (data.hasOwnProperty('processInstanceBusinessKey')) {
                obj['processInstanceBusinessKey'] = ApiClient.convertToType(data['processInstanceBusinessKey'], 'String');
            }
            if (data.hasOwnProperty('processInstanceBusinessKeyExpression')) {
                obj['processInstanceBusinessKeyExpression'] = ApiClient.convertToType(data['processInstanceBusinessKeyExpression'], 'String');
            }
            if (data.hasOwnProperty('processInstanceBusinessKeyIn')) {
                obj['processInstanceBusinessKeyIn'] = ApiClient.convertToType(data['processInstanceBusinessKeyIn'], ['String']);
            }
            if (data.hasOwnProperty('processInstanceBusinessKeyLike')) {
                obj['processInstanceBusinessKeyLike'] = ApiClient.convertToType(data['processInstanceBusinessKeyLike'], 'String');
            }
            if (data.hasOwnProperty('processInstanceBusinessKeyLikeExpression')) {
                obj['processInstanceBusinessKeyLikeExpression'] = ApiClient.convertToType(data['processInstanceBusinessKeyLikeExpression'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionId')) {
                obj['processDefinitionId'] = ApiClient.convertToType(data['processDefinitionId'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionKey')) {
                obj['processDefinitionKey'] = ApiClient.convertToType(data['processDefinitionKey'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionKeyIn')) {
                obj['processDefinitionKeyIn'] = ApiClient.convertToType(data['processDefinitionKeyIn'], ['String']);
            }
            if (data.hasOwnProperty('processDefinitionName')) {
                obj['processDefinitionName'] = ApiClient.convertToType(data['processDefinitionName'], 'String');
            }
            if (data.hasOwnProperty('processDefinitionNameLike')) {
                obj['processDefinitionNameLike'] = ApiClient.convertToType(data['processDefinitionNameLike'], 'String');
            }
            if (data.hasOwnProperty('executionId')) {
                obj['executionId'] = ApiClient.convertToType(data['executionId'], 'String');
            }
            if (data.hasOwnProperty('caseInstanceId')) {
                obj['caseInstanceId'] = ApiClient.convertToType(data['caseInstanceId'], 'String');
            }
            if (data.hasOwnProperty('caseInstanceBusinessKey')) {
                obj['caseInstanceBusinessKey'] = ApiClient.convertToType(data['caseInstanceBusinessKey'], 'String');
            }
            if (data.hasOwnProperty('caseInstanceBusinessKeyLike')) {
                obj['caseInstanceBusinessKeyLike'] = ApiClient.convertToType(data['caseInstanceBusinessKeyLike'], 'String');
            }
            if (data.hasOwnProperty('caseDefinitionId')) {
                obj['caseDefinitionId'] = ApiClient.convertToType(data['caseDefinitionId'], 'String');
            }
            if (data.hasOwnProperty('caseDefinitionKey')) {
                obj['caseDefinitionKey'] = ApiClient.convertToType(data['caseDefinitionKey'], 'String');
            }
            if (data.hasOwnProperty('caseDefinitionName')) {
                obj['caseDefinitionName'] = ApiClient.convertToType(data['caseDefinitionName'], 'String');
            }
            if (data.hasOwnProperty('caseDefinitionNameLike')) {
                obj['caseDefinitionNameLike'] = ApiClient.convertToType(data['caseDefinitionNameLike'], 'String');
            }
            if (data.hasOwnProperty('caseExecutionId')) {
                obj['caseExecutionId'] = ApiClient.convertToType(data['caseExecutionId'], 'String');
            }
            if (data.hasOwnProperty('activityInstanceIdIn')) {
                obj['activityInstanceIdIn'] = ApiClient.convertToType(data['activityInstanceIdIn'], ['String']);
            }
            if (data.hasOwnProperty('tenantIdIn')) {
                obj['tenantIdIn'] = ApiClient.convertToType(data['tenantIdIn'], ['String']);
            }
            if (data.hasOwnProperty('withoutTenantId')) {
                obj['withoutTenantId'] = ApiClient.convertToType(data['withoutTenantId'], 'Boolean');
            }
            if (data.hasOwnProperty('assignee')) {
                obj['assignee'] = ApiClient.convertToType(data['assignee'], 'String');
            }
            if (data.hasOwnProperty('assigneeExpression')) {
                obj['assigneeExpression'] = ApiClient.convertToType(data['assigneeExpression'], 'String');
            }
            if (data.hasOwnProperty('assigneeLike')) {
                obj['assigneeLike'] = ApiClient.convertToType(data['assigneeLike'], 'String');
            }
            if (data.hasOwnProperty('assigneeLikeExpression')) {
                obj['assigneeLikeExpression'] = ApiClient.convertToType(data['assigneeLikeExpression'], 'String');
            }
            if (data.hasOwnProperty('assigneeIn')) {
                obj['assigneeIn'] = ApiClient.convertToType(data['assigneeIn'], ['String']);
            }
            if (data.hasOwnProperty('owner')) {
                obj['owner'] = ApiClient.convertToType(data['owner'], 'String');
            }
            if (data.hasOwnProperty('ownerExpression')) {
                obj['ownerExpression'] = ApiClient.convertToType(data['ownerExpression'], 'String');
            }
            if (data.hasOwnProperty('candidateGroup')) {
                obj['candidateGroup'] = ApiClient.convertToType(data['candidateGroup'], 'String');
            }
            if (data.hasOwnProperty('candidateGroupExpression')) {
                obj['candidateGroupExpression'] = ApiClient.convertToType(data['candidateGroupExpression'], 'String');
            }
            if (data.hasOwnProperty('candidateUser')) {
                obj['candidateUser'] = ApiClient.convertToType(data['candidateUser'], 'String');
            }
            if (data.hasOwnProperty('candidateUserExpression')) {
                obj['candidateUserExpression'] = ApiClient.convertToType(data['candidateUserExpression'], 'String');
            }
            if (data.hasOwnProperty('includeAssignedTasks')) {
                obj['includeAssignedTasks'] = ApiClient.convertToType(data['includeAssignedTasks'], 'Boolean');
            }
            if (data.hasOwnProperty('involvedUser')) {
                obj['involvedUser'] = ApiClient.convertToType(data['involvedUser'], 'String');
            }
            if (data.hasOwnProperty('involvedUserExpression')) {
                obj['involvedUserExpression'] = ApiClient.convertToType(data['involvedUserExpression'], 'String');
            }
            if (data.hasOwnProperty('assigned')) {
                obj['assigned'] = ApiClient.convertToType(data['assigned'], 'Boolean');
            }
            if (data.hasOwnProperty('unassigned')) {
                obj['unassigned'] = ApiClient.convertToType(data['unassigned'], 'Boolean');
            }
            if (data.hasOwnProperty('taskDefinitionKey')) {
                obj['taskDefinitionKey'] = ApiClient.convertToType(data['taskDefinitionKey'], 'String');
            }
            if (data.hasOwnProperty('taskDefinitionKeyIn')) {
                obj['taskDefinitionKeyIn'] = ApiClient.convertToType(data['taskDefinitionKeyIn'], ['String']);
            }
            if (data.hasOwnProperty('taskDefinitionKeyLike')) {
                obj['taskDefinitionKeyLike'] = ApiClient.convertToType(data['taskDefinitionKeyLike'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('nameNotEqual')) {
                obj['nameNotEqual'] = ApiClient.convertToType(data['nameNotEqual'], 'String');
            }
            if (data.hasOwnProperty('nameLike')) {
                obj['nameLike'] = ApiClient.convertToType(data['nameLike'], 'String');
            }
            if (data.hasOwnProperty('nameNotLike')) {
                obj['nameNotLike'] = ApiClient.convertToType(data['nameNotLike'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('descriptionLike')) {
                obj['descriptionLike'] = ApiClient.convertToType(data['descriptionLike'], 'String');
            }
            if (data.hasOwnProperty('priority')) {
                obj['priority'] = ApiClient.convertToType(data['priority'], 'Number');
            }
            if (data.hasOwnProperty('maxPriority')) {
                obj['maxPriority'] = ApiClient.convertToType(data['maxPriority'], 'Number');
            }
            if (data.hasOwnProperty('minPriority')) {
                obj['minPriority'] = ApiClient.convertToType(data['minPriority'], 'Number');
            }
            if (data.hasOwnProperty('dueDate')) {
                obj['dueDate'] = ApiClient.convertToType(data['dueDate'], 'Date');
            }
            if (data.hasOwnProperty('dueDateExpression')) {
                obj['dueDateExpression'] = ApiClient.convertToType(data['dueDateExpression'], 'String');
            }
            if (data.hasOwnProperty('dueAfter')) {
                obj['dueAfter'] = ApiClient.convertToType(data['dueAfter'], 'Date');
            }
            if (data.hasOwnProperty('dueAfterExpression')) {
                obj['dueAfterExpression'] = ApiClient.convertToType(data['dueAfterExpression'], 'String');
            }
            if (data.hasOwnProperty('dueBefore')) {
                obj['dueBefore'] = ApiClient.convertToType(data['dueBefore'], 'Date');
            }
            if (data.hasOwnProperty('dueBeforeExpression')) {
                obj['dueBeforeExpression'] = ApiClient.convertToType(data['dueBeforeExpression'], 'String');
            }
            if (data.hasOwnProperty('followUpDate')) {
                obj['followUpDate'] = ApiClient.convertToType(data['followUpDate'], 'Date');
            }
            if (data.hasOwnProperty('followUpDateExpression')) {
                obj['followUpDateExpression'] = ApiClient.convertToType(data['followUpDateExpression'], 'String');
            }
            if (data.hasOwnProperty('followUpAfter')) {
                obj['followUpAfter'] = ApiClient.convertToType(data['followUpAfter'], 'Date');
            }
            if (data.hasOwnProperty('followUpAfterExpression')) {
                obj['followUpAfterExpression'] = ApiClient.convertToType(data['followUpAfterExpression'], 'String');
            }
            if (data.hasOwnProperty('followUpBefore')) {
                obj['followUpBefore'] = ApiClient.convertToType(data['followUpBefore'], 'String');
            }
            if (data.hasOwnProperty('followUpBeforeExpression')) {
                obj['followUpBeforeExpression'] = ApiClient.convertToType(data['followUpBeforeExpression'], 'String');
            }
            if (data.hasOwnProperty('followUpBeforeOrNotExistent')) {
                obj['followUpBeforeOrNotExistent'] = ApiClient.convertToType(data['followUpBeforeOrNotExistent'], 'Date');
            }
            if (data.hasOwnProperty('followUpBeforeOrNotExistentExpression')) {
                obj['followUpBeforeOrNotExistentExpression'] = ApiClient.convertToType(data['followUpBeforeOrNotExistentExpression'], 'String');
            }
            if (data.hasOwnProperty('createdOn')) {
                obj['createdOn'] = ApiClient.convertToType(data['createdOn'], 'Date');
            }
            if (data.hasOwnProperty('createdOnExpression')) {
                obj['createdOnExpression'] = ApiClient.convertToType(data['createdOnExpression'], 'String');
            }
            if (data.hasOwnProperty('createdAfter')) {
                obj['createdAfter'] = ApiClient.convertToType(data['createdAfter'], 'Date');
            }
            if (data.hasOwnProperty('createdAfterExpression')) {
                obj['createdAfterExpression'] = ApiClient.convertToType(data['createdAfterExpression'], 'String');
            }
            if (data.hasOwnProperty('createdBefore')) {
                obj['createdBefore'] = ApiClient.convertToType(data['createdBefore'], 'Date');
            }
            if (data.hasOwnProperty('createdBeforeExpression')) {
                obj['createdBeforeExpression'] = ApiClient.convertToType(data['createdBeforeExpression'], 'String');
            }
            if (data.hasOwnProperty('delegationState')) {
                obj['delegationState'] = ApiClient.convertToType(data['delegationState'], 'String');
            }
            if (data.hasOwnProperty('candidateGroups')) {
                obj['candidateGroups'] = ApiClient.convertToType(data['candidateGroups'], ['String']);
            }
            if (data.hasOwnProperty('candidateGroupsExpression')) {
                obj['candidateGroupsExpression'] = ApiClient.convertToType(data['candidateGroupsExpression'], 'String');
            }
            if (data.hasOwnProperty('withCandidateGroups')) {
                obj['withCandidateGroups'] = ApiClient.convertToType(data['withCandidateGroups'], 'Boolean');
            }
            if (data.hasOwnProperty('withoutCandidateGroups')) {
                obj['withoutCandidateGroups'] = ApiClient.convertToType(data['withoutCandidateGroups'], 'Boolean');
            }
            if (data.hasOwnProperty('withCandidateUsers')) {
                obj['withCandidateUsers'] = ApiClient.convertToType(data['withCandidateUsers'], 'Boolean');
            }
            if (data.hasOwnProperty('withoutCandidateUsers')) {
                obj['withoutCandidateUsers'] = ApiClient.convertToType(data['withoutCandidateUsers'], 'Boolean');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('suspended')) {
                obj['suspended'] = ApiClient.convertToType(data['suspended'], 'Boolean');
            }
            if (data.hasOwnProperty('taskVariables')) {
                obj['taskVariables'] = ApiClient.convertToType(data['taskVariables'], [VariableQueryParameterDto]);
            }
            if (data.hasOwnProperty('processVariables')) {
                obj['processVariables'] = ApiClient.convertToType(data['processVariables'], [VariableQueryParameterDto]);
            }
            if (data.hasOwnProperty('caseInstanceVariables')) {
                obj['caseInstanceVariables'] = ApiClient.convertToType(data['caseInstanceVariables'], [VariableQueryParameterDto]);
            }
            if (data.hasOwnProperty('variableNamesIgnoreCase')) {
                obj['variableNamesIgnoreCase'] = ApiClient.convertToType(data['variableNamesIgnoreCase'], 'Boolean');
            }
            if (data.hasOwnProperty('variableValuesIgnoreCase')) {
                obj['variableValuesIgnoreCase'] = ApiClient.convertToType(data['variableValuesIgnoreCase'], 'Boolean');
            }
            if (data.hasOwnProperty('parentTaskId')) {
                obj['parentTaskId'] = ApiClient.convertToType(data['parentTaskId'], 'String');
            }
            if (data.hasOwnProperty('orQueries')) {
                obj['orQueries'] = ApiClient.convertToType(data['orQueries'], [TaskQueryDto]);
            }
            if (data.hasOwnProperty('sorting')) {
                obj['sorting'] = ApiClient.convertToType(data['sorting'], [TaskQueryDtoSorting]);
            }
        }
        return obj;
    }


}

/**
 * Restrict to tasks that belong to process instances with the given id.
 * @member {String} processInstanceId
 */
TaskQueryDto.prototype['processInstanceId'] = undefined;

/**
 * Restrict to tasks that belong to process instances with the given ids.
 * @member {Array.<String>} processInstanceIdIn
 */
TaskQueryDto.prototype['processInstanceIdIn'] = undefined;

/**
 * Restrict to tasks that belong to process instances with the given business key.
 * @member {String} processInstanceBusinessKey
 */
TaskQueryDto.prototype['processInstanceBusinessKey'] = undefined;

/**
 * Restrict to tasks that belong to process instances with the given business key which  is described by an expression. See the  [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions.
 * @member {String} processInstanceBusinessKeyExpression
 */
TaskQueryDto.prototype['processInstanceBusinessKeyExpression'] = undefined;

/**
 * Restrict to tasks that belong to process instances with one of the give business keys.  The keys need to be in a comma-separated list.
 * @member {Array.<String>} processInstanceBusinessKeyIn
 */
TaskQueryDto.prototype['processInstanceBusinessKeyIn'] = undefined;

/**
 * Restrict to tasks that have a process instance business key that has the parameter  value as a substring.
 * @member {String} processInstanceBusinessKeyLike
 */
TaskQueryDto.prototype['processInstanceBusinessKeyLike'] = undefined;

/**
 * Restrict to tasks that have a process instance business key that has the parameter  value as a substring and is described by an expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions)  for more information on available functions.
 * @member {String} processInstanceBusinessKeyLikeExpression
 */
TaskQueryDto.prototype['processInstanceBusinessKeyLikeExpression'] = undefined;

/**
 * Restrict to tasks that belong to a process definition with the given id.
 * @member {String} processDefinitionId
 */
TaskQueryDto.prototype['processDefinitionId'] = undefined;

/**
 * Restrict to tasks that belong to a process definition with the given key.
 * @member {String} processDefinitionKey
 */
TaskQueryDto.prototype['processDefinitionKey'] = undefined;

/**
 * Restrict to tasks that belong to a process definition with one of the given keys. The  keys need to be in a comma-separated list.
 * @member {Array.<String>} processDefinitionKeyIn
 */
TaskQueryDto.prototype['processDefinitionKeyIn'] = undefined;

/**
 * Restrict to tasks that belong to a process definition with the given name.
 * @member {String} processDefinitionName
 */
TaskQueryDto.prototype['processDefinitionName'] = undefined;

/**
 * Restrict to tasks that have a process definition name that has the parameter value as  a substring.
 * @member {String} processDefinitionNameLike
 */
TaskQueryDto.prototype['processDefinitionNameLike'] = undefined;

/**
 * Restrict to tasks that belong to an execution with the given id.
 * @member {String} executionId
 */
TaskQueryDto.prototype['executionId'] = undefined;

/**
 * Restrict to tasks that belong to case instances with the given id.
 * @member {String} caseInstanceId
 */
TaskQueryDto.prototype['caseInstanceId'] = undefined;

/**
 * Restrict to tasks that belong to case instances with the given business key.
 * @member {String} caseInstanceBusinessKey
 */
TaskQueryDto.prototype['caseInstanceBusinessKey'] = undefined;

/**
 * Restrict to tasks that have a case instance business key that has the parameter value  as a substring.
 * @member {String} caseInstanceBusinessKeyLike
 */
TaskQueryDto.prototype['caseInstanceBusinessKeyLike'] = undefined;

/**
 * Restrict to tasks that belong to a case definition with the given id.
 * @member {String} caseDefinitionId
 */
TaskQueryDto.prototype['caseDefinitionId'] = undefined;

/**
 * Restrict to tasks that belong to a case definition with the given key.
 * @member {String} caseDefinitionKey
 */
TaskQueryDto.prototype['caseDefinitionKey'] = undefined;

/**
 * Restrict to tasks that belong to a case definition with the given name.
 * @member {String} caseDefinitionName
 */
TaskQueryDto.prototype['caseDefinitionName'] = undefined;

/**
 * Restrict to tasks that have a case definition name that has the parameter value as a  substring.
 * @member {String} caseDefinitionNameLike
 */
TaskQueryDto.prototype['caseDefinitionNameLike'] = undefined;

/**
 * Restrict to tasks that belong to a case execution with the given id.
 * @member {String} caseExecutionId
 */
TaskQueryDto.prototype['caseExecutionId'] = undefined;

/**
 * Only include tasks which belong to one of the passed and comma-separated activity  instance ids.
 * @member {Array.<String>} activityInstanceIdIn
 */
TaskQueryDto.prototype['activityInstanceIdIn'] = undefined;

/**
 * Only include tasks which belong to one of the passed and comma-separated  tenant ids.
 * @member {Array.<String>} tenantIdIn
 */
TaskQueryDto.prototype['tenantIdIn'] = undefined;

/**
 * Only include tasks which belong to no tenant. Value may only be `true`,  as `false` is the default behavior.
 * @member {Boolean} withoutTenantId
 * @default false
 */
TaskQueryDto.prototype['withoutTenantId'] = false;

/**
 * Restrict to tasks that the given user is assigned to.
 * @member {String} assignee
 */
TaskQueryDto.prototype['assignee'] = undefined;

/**
 * Restrict to tasks that the user described by the given expression is assigned to. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions)  for more information on available functions.
 * @member {String} assigneeExpression
 */
TaskQueryDto.prototype['assigneeExpression'] = undefined;

/**
 * Restrict to tasks that have an assignee that has the parameter  value as a substring.
 * @member {String} assigneeLike
 */
TaskQueryDto.prototype['assigneeLike'] = undefined;

/**
 * Restrict to tasks that have an assignee that has the parameter value described by the  given expression as a substring. See the  [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions)  for more information on available functions.
 * @member {String} assigneeLikeExpression
 */
TaskQueryDto.prototype['assigneeLikeExpression'] = undefined;

/**
 * Only include tasks which are assigned to one of the passed and comma-separated user ids.
 * @member {Array.<String>} assigneeIn
 */
TaskQueryDto.prototype['assigneeIn'] = undefined;

/**
 * Restrict to tasks that the given user owns.
 * @member {String} owner
 */
TaskQueryDto.prototype['owner'] = undefined;

/**
 * Restrict to tasks that the user described by the given expression owns. See the  [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions)  for more information on available functions.
 * @member {String} ownerExpression
 */
TaskQueryDto.prototype['ownerExpression'] = undefined;

/**
 * Only include tasks that are offered to the given group.
 * @member {String} candidateGroup
 */
TaskQueryDto.prototype['candidateGroup'] = undefined;

/**
 * Only include tasks that are offered to the group described by the given expression.  See the  [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions)  for more information on available functions.
 * @member {String} candidateGroupExpression
 */
TaskQueryDto.prototype['candidateGroupExpression'] = undefined;

/**
 * Only include tasks that are offered to the given user or to one of his groups.
 * @member {String} candidateUser
 */
TaskQueryDto.prototype['candidateUser'] = undefined;

/**
 * Only include tasks that are offered to the user described by the given expression.  See the  [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions)  for more information on available functions.
 * @member {String} candidateUserExpression
 */
TaskQueryDto.prototype['candidateUserExpression'] = undefined;

/**
 * Also include tasks that are assigned to users in candidate queries. Default is to only  include tasks that are not assigned to any user if you query by candidate user or group(s).
 * @member {Boolean} includeAssignedTasks
 * @default false
 */
TaskQueryDto.prototype['includeAssignedTasks'] = false;

/**
 * Only include tasks that the given user is involved in. A user is involved in a task if  an identity link exists between task and user (e.g., the user is the assignee).
 * @member {String} involvedUser
 */
TaskQueryDto.prototype['involvedUser'] = undefined;

/**
 * Only include tasks that the user described by the given expression is involved in. A user is involved in a task if an identity link exists between task and user (e.g., the user is the assignee). See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions.
 * @member {String} involvedUserExpression
 */
TaskQueryDto.prototype['involvedUserExpression'] = undefined;

/**
 * If set to `true`, restricts the query to all tasks that are assigned.
 * @member {Boolean} assigned
 * @default false
 */
TaskQueryDto.prototype['assigned'] = false;

/**
 * If set to `true`, restricts the query to all tasks that are unassigned.
 * @member {Boolean} unassigned
 * @default false
 */
TaskQueryDto.prototype['unassigned'] = false;

/**
 * Restrict to tasks that have the given key.
 * @member {String} taskDefinitionKey
 */
TaskQueryDto.prototype['taskDefinitionKey'] = undefined;

/**
 * Restrict to tasks that have one of the given keys. The keys need to be in a comma-separated list.
 * @member {Array.<String>} taskDefinitionKeyIn
 */
TaskQueryDto.prototype['taskDefinitionKeyIn'] = undefined;

/**
 * Restrict to tasks that have a key that has the parameter value as a substring.
 * @member {String} taskDefinitionKeyLike
 */
TaskQueryDto.prototype['taskDefinitionKeyLike'] = undefined;

/**
 * Restrict to tasks that have the given name.
 * @member {String} name
 */
TaskQueryDto.prototype['name'] = undefined;

/**
 * Restrict to tasks that do not have the given name.
 * @member {String} nameNotEqual
 */
TaskQueryDto.prototype['nameNotEqual'] = undefined;

/**
 * Restrict to tasks that have a name with the given parameter value as substring.
 * @member {String} nameLike
 */
TaskQueryDto.prototype['nameLike'] = undefined;

/**
 * Restrict to tasks that do not have a name with the given parameter value as substring.
 * @member {String} nameNotLike
 */
TaskQueryDto.prototype['nameNotLike'] = undefined;

/**
 * Restrict to tasks that have the given description.
 * @member {String} description
 */
TaskQueryDto.prototype['description'] = undefined;

/**
 * Restrict to tasks that have a description that has the parameter value as a substring.
 * @member {String} descriptionLike
 */
TaskQueryDto.prototype['descriptionLike'] = undefined;

/**
 * Restrict to tasks that have the given priority.
 * @member {Number} priority
 */
TaskQueryDto.prototype['priority'] = undefined;

/**
 * Restrict to tasks that have a lower or equal priority.
 * @member {Number} maxPriority
 */
TaskQueryDto.prototype['maxPriority'] = undefined;

/**
 * Restrict to tasks that have a higher or equal priority.
 * @member {Number} minPriority
 */
TaskQueryDto.prototype['minPriority'] = undefined;

/**
 * Restrict to tasks that are due on the given date. By [default](https://docs.camunda.org/manual/7.14/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.546+0200`.
 * @member {Date} dueDate
 */
TaskQueryDto.prototype['dueDate'] = undefined;

/**
 * Restrict to tasks that are due on the date described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to a `java.util.Date` or `org.joda.time.DateTime` object.
 * @member {String} dueDateExpression
 */
TaskQueryDto.prototype['dueDateExpression'] = undefined;

/**
 * Restrict to tasks that are due after the given date. By [default](https://docs.camunda.org/manual/7.14/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.435+0200`.
 * @member {Date} dueAfter
 */
TaskQueryDto.prototype['dueAfter'] = undefined;

/**
 * Restrict to tasks that are due after the date described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to a `java.util.Date` or `org.joda.time.DateTime` object.
 * @member {String} dueAfterExpression
 */
TaskQueryDto.prototype['dueAfterExpression'] = undefined;

/**
 * Restrict to tasks that are due before the given date. By [default](https://docs.camunda.org/manual/7.14/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.243+0200`.
 * @member {Date} dueBefore
 */
TaskQueryDto.prototype['dueBefore'] = undefined;

/**
 * Restrict to tasks that are due before the date described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to a `java.util.Date` or `org.joda.time.DateTime` object.
 * @member {String} dueBeforeExpression
 */
TaskQueryDto.prototype['dueBeforeExpression'] = undefined;

/**
 * Restrict to tasks that have a followUp date on the given date. By [default](https://docs.camunda.org/manual/7.14/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.342+0200`.
 * @member {Date} followUpDate
 */
TaskQueryDto.prototype['followUpDate'] = undefined;

/**
 * Restrict to tasks that have a followUp date on the date described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to a `java.util.Date` or `org.joda.time.DateTime` object.
 * @member {String} followUpDateExpression
 */
TaskQueryDto.prototype['followUpDateExpression'] = undefined;

/**
 * Restrict to tasks that have a followUp date after the given date. By [default](https://docs.camunda.org/manual/7.14/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.542+0200`.
 * @member {Date} followUpAfter
 */
TaskQueryDto.prototype['followUpAfter'] = undefined;

/**
 * Restrict to tasks that have a followUp date after the date described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to a `java.util.Date` or `org.joda.time.DateTime` object.
 * @member {String} followUpAfterExpression
 */
TaskQueryDto.prototype['followUpAfterExpression'] = undefined;

/**
 * Restrict to tasks that have a followUp date before the given date. By [default](https://docs.camunda.org/manual/7.14/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.234+0200`.
 * @member {String} followUpBefore
 */
TaskQueryDto.prototype['followUpBefore'] = undefined;

/**
 * Restrict to tasks that have a followUp date before the date described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to a `java.util.Date` or `org.joda.time.DateTime` object.
 * @member {String} followUpBeforeExpression
 */
TaskQueryDto.prototype['followUpBeforeExpression'] = undefined;

/**
 * Restrict to tasks that have no followUp date or a followUp date before the given date. By [default](https://docs.camunda.org/manual/7.14/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.432+0200`. The typical use case is to query all `active` tasks for a user for a given date.
 * @member {Date} followUpBeforeOrNotExistent
 */
TaskQueryDto.prototype['followUpBeforeOrNotExistent'] = undefined;

/**
 * Restrict to tasks that have no followUp date or a followUp date before the date described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to a `java.util.Date` or `org.joda.time.DateTime` object.
 * @member {String} followUpBeforeOrNotExistentExpression
 */
TaskQueryDto.prototype['followUpBeforeOrNotExistentExpression'] = undefined;

/**
 * Restrict to tasks that were created on the given date. By [default](https://docs.camunda.org/manual/7.14/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.324+0200`.
 * @member {Date} createdOn
 */
TaskQueryDto.prototype['createdOn'] = undefined;

/**
 * Restrict to tasks that were created on the date described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to a `java.util.Date` or `org.joda.time.DateTime` object.
 * @member {String} createdOnExpression
 */
TaskQueryDto.prototype['createdOnExpression'] = undefined;

/**
 * Restrict to tasks that were created after the given date. By [default](https://docs.camunda.org/manual/7.14/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.342+0200`.
 * @member {Date} createdAfter
 */
TaskQueryDto.prototype['createdAfter'] = undefined;

/**
 * Restrict to tasks that were created after the date described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to a `java.util.Date` or `org.joda.time.DateTime` object.
 * @member {String} createdAfterExpression
 */
TaskQueryDto.prototype['createdAfterExpression'] = undefined;

/**
 * Restrict to tasks that were created before the given date. By [default](https://docs.camunda.org/manual/7.14/reference/rest/overview/date-format/), the date must have the format `yyyy-MM-dd'T'HH:mm:ss.SSSZ`, e.g., `2013-01-23T14:42:45.332+0200`.
 * @member {Date} createdBefore
 */
TaskQueryDto.prototype['createdBefore'] = undefined;

/**
 * Restrict to tasks that were created before the date described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to a `java.util.Date` or `org.joda.time.DateTime` object.
 * @member {String} createdBeforeExpression
 */
TaskQueryDto.prototype['createdBeforeExpression'] = undefined;

/**
 * Restrict to tasks that are in the given delegation state. Valid values are `PENDING` and `RESOLVED`.
 * @member {module:model/TaskQueryDto.DelegationStateEnum} delegationState
 */
TaskQueryDto.prototype['delegationState'] = undefined;

/**
 * Restrict to tasks that are offered to any of the given candidate groups. Takes a comma-separated list of group names, so for example `developers,support,sales`.
 * @member {Array.<String>} candidateGroups
 */
TaskQueryDto.prototype['candidateGroups'] = undefined;

/**
 * Restrict to tasks that are offered to any of the candidate groups described by the given expression. See the [user guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/expression-language/#internal-context-functions) for more information on available functions. The expression must evaluate to `java.util.List` of Strings.
 * @member {String} candidateGroupsExpression
 */
TaskQueryDto.prototype['candidateGroupsExpression'] = undefined;

/**
 * Only include tasks which have a candidate group. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} withCandidateGroups
 * @default false
 */
TaskQueryDto.prototype['withCandidateGroups'] = false;

/**
 * Only include tasks which have no candidate group. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} withoutCandidateGroups
 * @default false
 */
TaskQueryDto.prototype['withoutCandidateGroups'] = false;

/**
 * Only include tasks which have a candidate user. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} withCandidateUsers
 * @default false
 */
TaskQueryDto.prototype['withCandidateUsers'] = false;

/**
 * Only include tasks which have no candidate users. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} withoutCandidateUsers
 * @default false
 */
TaskQueryDto.prototype['withoutCandidateUsers'] = false;

/**
 * Only include active tasks. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} active
 * @default false
 */
TaskQueryDto.prototype['active'] = false;

/**
 * Only include suspended tasks. Value may only be `true`, as `false` is the default behavior.
 * @member {Boolean} suspended
 * @default false
 */
TaskQueryDto.prototype['suspended'] = false;

/**
 * A JSON array to only include tasks that have variables with certain values. The array consists of JSON objects with three properties `name`, `operator` and `value`. `name` is the variable name, `operator` is the comparison operator to be used and `value` the variable value. `value` may be of type `String`, `Number` or `Boolean`.  Valid `operator` values are: `eq` - equal to; `neq` - not equal to; `gt` - greater than; `gteq` - greater than or equal to; `lt` - lower than; `lteq` - lower than or equal to; `like`. `key` and `value` may not contain underscore or comma characters.
 * @member {Array.<module:model/VariableQueryParameterDto>} taskVariables
 */
TaskQueryDto.prototype['taskVariables'] = undefined;

/**
 * A JSON array to only include tasks that belong to a process instance with variables with certain values. The array consists of JSON objects with three properties `name`, `operator` and `value`. `name` is the variable name, `operator` is the comparison operator to be used and `value` the variable value. `value` may be of type `String`, `Number` or `Boolean`.  Valid `operator` values are: `eq` - equal to; `neq` - not equal to; `gt` - greater than; `gteq` - greater than or equal to; `lt` - lower than; `lteq` - lower than or equal to; `like`. `key` and `value` may not contain underscore or comma characters.
 * @member {Array.<module:model/VariableQueryParameterDto>} processVariables
 */
TaskQueryDto.prototype['processVariables'] = undefined;

/**
 * A JSON array to only include tasks that belong to a case instance with variables with certain values. The array consists of JSON objects with three properties `name`, `operator` and `value`. `name` is the variable name, `operator` is the comparison operator to be used and `value` the variable value. `value` may be of type `String`, `Number` or `Boolean`.  Valid `operator` values are: `eq` - equal to; `neq` - not equal to; `gt` - greater than; `gteq` - greater than or equal to; `lt` - lower than; `lteq` - lower than or equal to; `like`. `key` and `value` may not contain underscore or comma characters.
 * @member {Array.<module:model/VariableQueryParameterDto>} caseInstanceVariables
 */
TaskQueryDto.prototype['caseInstanceVariables'] = undefined;

/**
 * Match all variable names in this query case-insensitively. If set `variableName` and `variablename` are treated as equal.
 * @member {Boolean} variableNamesIgnoreCase
 * @default false
 */
TaskQueryDto.prototype['variableNamesIgnoreCase'] = false;

/**
 * Match all variable values in this query case-insensitively. If set `variableValue` and `variablevalue` are treated as equal.
 * @member {Boolean} variableValuesIgnoreCase
 * @default false
 */
TaskQueryDto.prototype['variableValuesIgnoreCase'] = false;

/**
 * Restrict query to all tasks that are sub tasks of the given task. Takes a task id.
 * @member {String} parentTaskId
 */
TaskQueryDto.prototype['parentTaskId'] = undefined;

/**
 * A JSON array of nested task queries with OR semantics. A task matches a nested query if it fulfills *at least one* of the query's predicates. With multiple nested queries, a task must fulfill at least one predicate of *each* query ([Conjunctive Normal Form](https://en.wikipedia.org/wiki/Conjunctive_normal_form)).  All task query properties can be used except for: `sorting`, `withCandidateGroups`, `withoutCandidateGroups`, `withCandidateUsers`, `withoutCandidateUsers`  See the [User guide](https://docs.camunda.org/manual/7.14/user-guide/process-engine/process-engine-api/#or-queries) for more information about OR queries.
 * @member {Array.<module:model/TaskQueryDto>} orQueries
 */
TaskQueryDto.prototype['orQueries'] = undefined;

/**
 * Apply sorting of the result
 * @member {Array.<module:model/TaskQueryDtoSorting>} sorting
 */
TaskQueryDto.prototype['sorting'] = undefined;





/**
 * Allowed values for the <code>delegationState</code> property.
 * @enum {String}
 * @readonly
 */
TaskQueryDto['DelegationStateEnum'] = {

    /**
     * value: "PENDING"
     * @const
     */
    "PENDING": "PENDING",

    /**
     * value: "RESOLVED"
     * @const
     */
    "RESOLVED": "RESOLVED"
};



export default TaskQueryDto;

