/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TriggerVariableValueDtoAllOf model module.
 * @module model/TriggerVariableValueDtoAllOf
 * @version 7.14.0
 */
class TriggerVariableValueDtoAllOf {
    /**
     * Constructs a new <code>TriggerVariableValueDtoAllOf</code>.
     * @alias module:model/TriggerVariableValueDtoAllOf
     */
    constructor() { 
        
        TriggerVariableValueDtoAllOf.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TriggerVariableValueDtoAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TriggerVariableValueDtoAllOf} obj Optional instance to populate.
     * @return {module:model/TriggerVariableValueDtoAllOf} The populated <code>TriggerVariableValueDtoAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TriggerVariableValueDtoAllOf();

            if (data.hasOwnProperty('local')) {
                obj['local'] = ApiClient.convertToType(data['local'], 'Boolean');
            }
        }
        return obj;
    }


}

/**
 * Indicates whether the variable should be a local variable or not. If set to true, the variable becomes a local variable of the execution entering the target activity.
 * @member {Boolean} local
 */
TriggerVariableValueDtoAllOf.prototype['local'] = undefined;






export default TriggerVariableValueDtoAllOf;

