/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserCredentialsDto model module.
 * @module model/UserCredentialsDto
 * @version 7.14.0
 */
class UserCredentialsDto {
    /**
     * Constructs a new <code>UserCredentialsDto</code>.
     * @alias module:model/UserCredentialsDto
     */
    constructor() { 
        
        UserCredentialsDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserCredentialsDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserCredentialsDto} obj Optional instance to populate.
     * @return {module:model/UserCredentialsDto} The populated <code>UserCredentialsDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserCredentialsDto();

            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('authenticatedUserPassword')) {
                obj['authenticatedUserPassword'] = ApiClient.convertToType(data['authenticatedUserPassword'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The users new password.
 * @member {String} password
 */
UserCredentialsDto.prototype['password'] = undefined;

/**
 * The password of the authenticated user who changes the password of the user (i.e., the user with passed id as path parameter).
 * @member {String} authenticatedUserPassword
 */
UserCredentialsDto.prototype['authenticatedUserPassword'] = undefined;






export default UserCredentialsDto;

