/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthorizationExceptionDto from '../model/AuthorizationExceptionDto';
import CommentDto from '../model/CommentDto';
import ExceptionDto from '../model/ExceptionDto';

/**
* TaskComment service.
* @module api/TaskCommentApi
* @version 7.14.0
*/
export default class TaskCommentApi {

    /**
    * Constructs a new TaskCommentApi. 
    * @alias module:api/TaskCommentApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Creates a comment for a task by id.
     * @param {String} id The id of the task to add the comment to.
     * @param {Object} opts Optional parameters
     * @param {module:model/CommentDto} opts.commentDto **Note:** Only the `message` property will be used. Every other property passed to this endpoint will be ignored.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CommentDto} and HTTP response
     */
    createCommentWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = opts['commentDto'];
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling createComment");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = CommentDto;
      return this.apiClient.callApi(
        '/task/{id}/comment/create', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Creates a comment for a task by id.
     * @param {String} id The id of the task to add the comment to.
     * @param {Object} opts Optional parameters
     * @param {module:model/CommentDto} opts.commentDto **Note:** Only the `message` property will be used. Every other property passed to this endpoint will be ignored.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CommentDto}
     */
    createComment(id, opts) {
      return this.createCommentWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Retrieves a task comment by task id and comment id.
     * @param {String} id The id of the task.
     * @param {String} commentId The id of the comment to be retrieved.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/CommentDto} and HTTP response
     */
    getCommentWithHttpInfo(id, commentId) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getComment");
      }
      // verify the required parameter 'commentId' is set
      if (commentId === undefined || commentId === null) {
        throw new Error("Missing the required parameter 'commentId' when calling getComment");
      }

      let pathParams = {
        'id': id,
        'commentId': commentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = CommentDto;
      return this.apiClient.callApi(
        '/task/{id}/comment/{commentId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Retrieves a task comment by task id and comment id.
     * @param {String} id The id of the task.
     * @param {String} commentId The id of the comment to be retrieved.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/CommentDto}
     */
    getComment(id, commentId) {
      return this.getCommentWithHttpInfo(id, commentId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Gets the comments for a task by id.
     * @param {String} id The id of the task to retrieve the comments for.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CommentDto>} and HTTP response
     */
    getCommentsWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getComments");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CommentDto];
      return this.apiClient.callApi(
        '/task/{id}/comment', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Gets the comments for a task by id.
     * @param {String} id The id of the task to retrieve the comments for.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CommentDto>}
     */
    getComments(id) {
      return this.getCommentsWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
