/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaBpmRestApi);
  }
}(this, function(expect, CamundaBpmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaBpmRestApi.AttachmentDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AttachmentDto', function() {
    it('should create an instance of AttachmentDto', function() {
      // uncomment below and update the code to test AttachmentDto
      //var instane = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be.a(CamundaBpmRestApi.AttachmentDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be();
    });

    it('should have the property taskId (base name: "taskId")', function() {
      // uncomment below and update the code to test the property taskId
      //var instance = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be();
    });

    it('should have the property url (base name: "url")', function() {
      // uncomment below and update the code to test the property url
      //var instance = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be();
    });

    it('should have the property createTime (base name: "createTime")', function() {
      // uncomment below and update the code to test the property createTime
      //var instance = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be();
    });

    it('should have the property removalTime (base name: "removalTime")', function() {
      // uncomment below and update the code to test the property removalTime
      //var instance = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be();
    });

    it('should have the property rootProcessInstanceId (base name: "rootProcessInstanceId")', function() {
      // uncomment below and update the code to test the property rootProcessInstanceId
      //var instance = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be();
    });

    it('should have the property links (base name: "links")', function() {
      // uncomment below and update the code to test the property links
      //var instance = new CamundaBpmRestApi.AttachmentDto();
      //expect(instance).to.be();
    });

  });

}));
