/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaBpmRestApi);
  }
}(this, function(expect, CamundaBpmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaBpmRestApi.BatchDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BatchDto', function() {
    it('should create an instance of BatchDto', function() {
      // uncomment below and update the code to test BatchDto
      //var instane = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be.a(CamundaBpmRestApi.BatchDto);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property totalJobs (base name: "totalJobs")', function() {
      // uncomment below and update the code to test the property totalJobs
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property jobsCreated (base name: "jobsCreated")', function() {
      // uncomment below and update the code to test the property jobsCreated
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property batchJobsPerSeed (base name: "batchJobsPerSeed")', function() {
      // uncomment below and update the code to test the property batchJobsPerSeed
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property invocationsPerBatchJob (base name: "invocationsPerBatchJob")', function() {
      // uncomment below and update the code to test the property invocationsPerBatchJob
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property seedJobDefinitionId (base name: "seedJobDefinitionId")', function() {
      // uncomment below and update the code to test the property seedJobDefinitionId
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property monitorJobDefinitionId (base name: "monitorJobDefinitionId")', function() {
      // uncomment below and update the code to test the property monitorJobDefinitionId
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property batchJobDefinitionId (base name: "batchJobDefinitionId")', function() {
      // uncomment below and update the code to test the property batchJobDefinitionId
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property suspended (base name: "suspended")', function() {
      // uncomment below and update the code to test the property suspended
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property tenantId (base name: "tenantId")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

    it('should have the property createUserId (base name: "createUserId")', function() {
      // uncomment below and update the code to test the property createUserId
      //var instance = new CamundaBpmRestApi.BatchDto();
      //expect(instance).to.be();
    });

  });

}));
