/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaBpmRestApi);
  }
}(this, function(expect, CamundaBpmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EventSubscriptionQueryDto', function() {
    it('should create an instance of EventSubscriptionQueryDto', function() {
      // uncomment below and update the code to test EventSubscriptionQueryDto
      //var instane = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be.a(CamundaBpmRestApi.EventSubscriptionQueryDto);
    });

    it('should have the property eventSubscriptionId (base name: "eventSubscriptionId")', function() {
      // uncomment below and update the code to test the property eventSubscriptionId
      //var instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property eventName (base name: "eventName")', function() {
      // uncomment below and update the code to test the property eventName
      //var instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property eventType (base name: "eventType")', function() {
      // uncomment below and update the code to test the property eventType
      //var instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property executionId (base name: "executionId")', function() {
      // uncomment below and update the code to test the property executionId
      //var instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property processInstanceId (base name: "processInstanceId")', function() {
      // uncomment below and update the code to test the property processInstanceId
      //var instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property activityId (base name: "activityId")', function() {
      // uncomment below and update the code to test the property activityId
      //var instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property tenantIdIn (base name: "tenantIdIn")', function() {
      // uncomment below and update the code to test the property tenantIdIn
      //var instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property withoutTenantId (base name: "withoutTenantId")', function() {
      // uncomment below and update the code to test the property withoutTenantId
      //var instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property includeEventSubscriptionsWithoutTenantId (base name: "includeEventSubscriptionsWithoutTenantId")', function() {
      // uncomment below and update the code to test the property includeEventSubscriptionsWithoutTenantId
      //var instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property sorting (base name: "sorting")', function() {
      // uncomment below and update the code to test the property sorting
      //var instance = new CamundaBpmRestApi.EventSubscriptionQueryDto();
      //expect(instance).to.be();
    });

  });

}));
