/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaBpmRestApi);
  }
}(this, function(expect, CamundaBpmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProcessInstanceQueryDto', function() {
    it('should create an instance of ProcessInstanceQueryDto', function() {
      // uncomment below and update the code to test ProcessInstanceQueryDto
      //var instane = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be.a(CamundaBpmRestApi.ProcessInstanceQueryDto);
    });

    it('should have the property deploymentId (base name: "deploymentId")', function() {
      // uncomment below and update the code to test the property deploymentId
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionId (base name: "processDefinitionId")', function() {
      // uncomment below and update the code to test the property processDefinitionId
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionKey (base name: "processDefinitionKey")', function() {
      // uncomment below and update the code to test the property processDefinitionKey
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionKeyIn (base name: "processDefinitionKeyIn")', function() {
      // uncomment below and update the code to test the property processDefinitionKeyIn
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionKeyNotIn (base name: "processDefinitionKeyNotIn")', function() {
      // uncomment below and update the code to test the property processDefinitionKeyNotIn
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property businessKey (base name: "businessKey")', function() {
      // uncomment below and update the code to test the property businessKey
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property businessKeyLike (base name: "businessKeyLike")', function() {
      // uncomment below and update the code to test the property businessKeyLike
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property caseInstanceId (base name: "caseInstanceId")', function() {
      // uncomment below and update the code to test the property caseInstanceId
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property superProcessInstance (base name: "superProcessInstance")', function() {
      // uncomment below and update the code to test the property superProcessInstance
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property subProcessInstance (base name: "subProcessInstance")', function() {
      // uncomment below and update the code to test the property subProcessInstance
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property superCaseInstance (base name: "superCaseInstance")', function() {
      // uncomment below and update the code to test the property superCaseInstance
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property subCaseInstance (base name: "subCaseInstance")', function() {
      // uncomment below and update the code to test the property subCaseInstance
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property active (base name: "active")', function() {
      // uncomment below and update the code to test the property active
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property suspended (base name: "suspended")', function() {
      // uncomment below and update the code to test the property suspended
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property processInstanceIds (base name: "processInstanceIds")', function() {
      // uncomment below and update the code to test the property processInstanceIds
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property withIncident (base name: "withIncident")', function() {
      // uncomment below and update the code to test the property withIncident
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property incidentId (base name: "incidentId")', function() {
      // uncomment below and update the code to test the property incidentId
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property incidentType (base name: "incidentType")', function() {
      // uncomment below and update the code to test the property incidentType
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property incidentMessage (base name: "incidentMessage")', function() {
      // uncomment below and update the code to test the property incidentMessage
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property incidentMessageLike (base name: "incidentMessageLike")', function() {
      // uncomment below and update the code to test the property incidentMessageLike
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property tenantIdIn (base name: "tenantIdIn")', function() {
      // uncomment below and update the code to test the property tenantIdIn
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property withoutTenantId (base name: "withoutTenantId")', function() {
      // uncomment below and update the code to test the property withoutTenantId
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property processDefinitionWithoutTenantId (base name: "processDefinitionWithoutTenantId")', function() {
      // uncomment below and update the code to test the property processDefinitionWithoutTenantId
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property activityIdIn (base name: "activityIdIn")', function() {
      // uncomment below and update the code to test the property activityIdIn
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property rootProcessInstances (base name: "rootProcessInstances")', function() {
      // uncomment below and update the code to test the property rootProcessInstances
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property leafProcessInstances (base name: "leafProcessInstances")', function() {
      // uncomment below and update the code to test the property leafProcessInstances
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property variables (base name: "variables")', function() {
      // uncomment below and update the code to test the property variables
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property variableNamesIgnoreCase (base name: "variableNamesIgnoreCase")', function() {
      // uncomment below and update the code to test the property variableNamesIgnoreCase
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property variableValuesIgnoreCase (base name: "variableValuesIgnoreCase")', function() {
      // uncomment below and update the code to test the property variableValuesIgnoreCase
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property orQueries (base name: "orQueries")', function() {
      // uncomment below and update the code to test the property orQueries
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

    it('should have the property sorting (base name: "sorting")', function() {
      // uncomment below and update the code to test the property sorting
      //var instance = new CamundaBpmRestApi.ProcessInstanceQueryDto();
      //expect(instance).to.be();
    });

  });

}));
