/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaBpmRestApi);
  }
}(this, function(expect, CamundaBpmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaBpmRestApi.RestartProcessInstanceDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RestartProcessInstanceDto', function() {
    it('should create an instance of RestartProcessInstanceDto', function() {
      // uncomment below and update the code to test RestartProcessInstanceDto
      //var instane = new CamundaBpmRestApi.RestartProcessInstanceDto();
      //expect(instance).to.be.a(CamundaBpmRestApi.RestartProcessInstanceDto);
    });

    it('should have the property processInstanceIds (base name: "processInstanceIds")', function() {
      // uncomment below and update the code to test the property processInstanceIds
      //var instance = new CamundaBpmRestApi.RestartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property historicProcessInstanceQuery (base name: "historicProcessInstanceQuery")', function() {
      // uncomment below and update the code to test the property historicProcessInstanceQuery
      //var instance = new CamundaBpmRestApi.RestartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property skipCustomListeners (base name: "skipCustomListeners")', function() {
      // uncomment below and update the code to test the property skipCustomListeners
      //var instance = new CamundaBpmRestApi.RestartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property skipIoMappings (base name: "skipIoMappings")', function() {
      // uncomment below and update the code to test the property skipIoMappings
      //var instance = new CamundaBpmRestApi.RestartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property initialVariables (base name: "initialVariables")', function() {
      // uncomment below and update the code to test the property initialVariables
      //var instance = new CamundaBpmRestApi.RestartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property withoutBusinessKey (base name: "withoutBusinessKey")', function() {
      // uncomment below and update the code to test the property withoutBusinessKey
      //var instance = new CamundaBpmRestApi.RestartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property instructions (base name: "instructions")', function() {
      // uncomment below and update the code to test the property instructions
      //var instance = new CamundaBpmRestApi.RestartProcessInstanceDto();
      //expect(instance).to.be();
    });

  });

}));
