/**
 * Camunda BPM REST API
 * OpenApi Spec for Camunda BPM REST API.
 *
 * The version of the OpenAPI document: 7.14.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CamundaBpmRestApi);
  }
}(this, function(expect, CamundaBpmRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CamundaBpmRestApi.StartProcessInstanceDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('StartProcessInstanceDto', function() {
    it('should create an instance of StartProcessInstanceDto', function() {
      // uncomment below and update the code to test StartProcessInstanceDto
      //var instane = new CamundaBpmRestApi.StartProcessInstanceDto();
      //expect(instance).to.be.a(CamundaBpmRestApi.StartProcessInstanceDto);
    });

    it('should have the property businessKey (base name: "businessKey")', function() {
      // uncomment below and update the code to test the property businessKey
      //var instance = new CamundaBpmRestApi.StartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property variables (base name: "variables")', function() {
      // uncomment below and update the code to test the property variables
      //var instance = new CamundaBpmRestApi.StartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property caseInstanceId (base name: "caseInstanceId")', function() {
      // uncomment below and update the code to test the property caseInstanceId
      //var instance = new CamundaBpmRestApi.StartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property startInstructions (base name: "startInstructions")', function() {
      // uncomment below and update the code to test the property startInstructions
      //var instance = new CamundaBpmRestApi.StartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property skipCustomListeners (base name: "skipCustomListeners")', function() {
      // uncomment below and update the code to test the property skipCustomListeners
      //var instance = new CamundaBpmRestApi.StartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property skipIoMappings (base name: "skipIoMappings")', function() {
      // uncomment below and update the code to test the property skipIoMappings
      //var instance = new CamundaBpmRestApi.StartProcessInstanceDto();
      //expect(instance).to.be();
    });

    it('should have the property withVariablesInReturn (base name: "withVariablesInReturn")', function() {
      // uncomment below and update the code to test the property withVariablesInReturn
      //var instance = new CamundaBpmRestApi.StartProcessInstanceDto();
      //expect(instance).to.be();
    });

  });

}));
